/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFAZ;

/**
 *
 * @author MASB
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REGISTRO = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JLabel();
        PRIMERAPELLIDO = new javax.swing.JLabel();
        SEGUNDOAPELIDO = new javax.swing.JLabel();
        CORREO = new javax.swing.JLabel();
        CONTRASENIA = new javax.swing.JLabel();
        CONTRASENIA1 = new javax.swing.JLabel();
        REGISTRARSE = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        NOMBRE1 = new javax.swing.JTextField();
        APELLIDO1 = new javax.swing.JTextField();
        correoelec = new javax.swing.JTextField();
        APELLIDO2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        REGISTRO.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        REGISTRO.setText("R E G I S T R O ");
        getContentPane().add(REGISTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        NOMBRE.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        NOMBRE.setText("Nombre : ");
        getContentPane().add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        PRIMERAPELLIDO.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        PRIMERAPELLIDO.setText("Primer apellido :");
        getContentPane().add(PRIMERAPELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        SEGUNDOAPELIDO.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        SEGUNDOAPELIDO.setText("Segundo apellido : ");
        getContentPane().add(SEGUNDOAPELIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        CORREO.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        CORREO.setText("Correo :");
        getContentPane().add(CORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        CONTRASENIA.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        CONTRASENIA.setText("Contraseña :");
        getContentPane().add(CONTRASENIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        CONTRASENIA1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        CONTRASENIA1.setText("Confirmar contraseña :");
        getContentPane().add(CONTRASENIA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        REGISTRARSE.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        REGISTRARSE.setText("REGISTRARSE ");
        REGISTRARSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRARSEActionPerformed(evt);
            }
        });
        getContentPane().add(REGISTRARSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        CANCELAR.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        CANCELAR.setText("CANCELAR ");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });
        getContentPane().add(CANCELAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        NOMBRE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMBRE1ActionPerformed(evt);
            }
        });
        getContentPane().add(NOMBRE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 250, 30));
        getContentPane().add(APELLIDO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 170, 30));
        getContentPane().add(correoelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 240, 30));
        getContentPane().add(APELLIDO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 160, 30));

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 180, 30));

        jPasswordField2.setText("jPasswordField1");
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 180, 30));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        jLabel1.setText("PUBLIC VENDING ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/56-567472_gradient-ombre-blue-watercolor-background.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void REGISTRARSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRARSEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGISTRARSEActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANCELARActionPerformed

    private void NOMBRE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMBRE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMBRE1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField APELLIDO1;
    private javax.swing.JTextField APELLIDO2;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JLabel CONTRASENIA;
    private javax.swing.JLabel CONTRASENIA1;
    private javax.swing.JLabel CORREO;
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JTextField NOMBRE1;
    private javax.swing.JLabel PRIMERAPELLIDO;
    private javax.swing.JButton REGISTRARSE;
    private javax.swing.JLabel REGISTRO;
    private javax.swing.JLabel SEGUNDOAPELIDO;
    private javax.swing.JTextField correoelec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables
}
