/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFAZ;

/**
 *
 * @author MASB
 */
public class VENDEDOR extends javax.swing.JFrame {

    /**
     * Creates new form VENDEDOR
     */
    public VENDEDOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VENTA = new javax.swing.JLabel();
        DATOSDELCLIENTE = new javax.swing.JLabel();
        TELEFONO = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JLabel();
        PAGO = new javax.swing.JLabel();
        ANOTACIONES = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        RECIBO = new javax.swing.JToggleButton();
        RegresarPre = new javax.swing.JToggleButton();
        cancelarVenta = new javax.swing.JToggleButton();
        ListaDePago = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VENTA.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 53)); // NOI18N
        VENTA.setText("V E N T A");
        getContentPane().add(VENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 50));

        DATOSDELCLIENTE.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        DATOSDELCLIENTE.setText("Datos del cliente ");
        getContentPane().add(DATOSDELCLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        TELEFONO.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        TELEFONO.setText("TELÉFONO:");
        getContentPane().add(TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        NOMBRE.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        NOMBRE.setText("NOMBRE:");
        getContentPane().add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        PAGO.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        PAGO.setText("PAGO: ");
        getContentPane().add(PAGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        ANOTACIONES.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        ANOTACIONES.setText("ANOTACIONES :");
        getContentPane().add(ANOTACIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 40));

        Nombre.setBackground(new java.awt.Color(0, 211, 201));
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 250, 30));

        telefono.setBackground(new java.awt.Color(0, 211, 201));
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 30));

        RECIBO.setBackground(new java.awt.Color(204, 255, 204));
        RECIBO.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        RECIBO.setText("Generar Recibo ");
        RECIBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECIBOActionPerformed(evt);
            }
        });
        getContentPane().add(RECIBO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        RegresarPre.setBackground(new java.awt.Color(204, 255, 204));
        RegresarPre.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        RegresarPre.setText("Regresar a presupuesto ");
        RegresarPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarPreActionPerformed(evt);
            }
        });
        getContentPane().add(RegresarPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, -1, -1));

        cancelarVenta.setBackground(new java.awt.Color(204, 255, 204));
        cancelarVenta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cancelarVenta.setText("Cancelar Venta");
        cancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVentaActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        ListaDePago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ListaDePago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total", "A cuenta" }));
        ListaDePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaDePagoActionPerformed(evt);
            }
        });
        getContentPane().add(ListaDePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 160, 30));

        jTextArea1.setBackground(new java.awt.Color(0, 211, 201));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 450, 150));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/56-567472_gradient-ombre-blue-watercolor-background.jpg"))); // NOI18N
        FONDO.setText("jLabel1");
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void RECIBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECIBOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RECIBOActionPerformed

    private void RegresarPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarPreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarPreActionPerformed

    private void cancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarVentaActionPerformed

    private void ListaDePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaDePagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaDePagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VENDEDOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VENDEDOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VENDEDOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VENDEDOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VENDEDOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANOTACIONES;
    private javax.swing.JLabel DATOSDELCLIENTE;
    private javax.swing.JLabel FONDO;
    private javax.swing.JComboBox<String> ListaDePago;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel PAGO;
    private javax.swing.JToggleButton RECIBO;
    private javax.swing.JToggleButton RegresarPre;
    private javax.swing.JLabel TELEFONO;
    private javax.swing.JLabel VENTA;
    private javax.swing.JToggleButton cancelarVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
